events {}
http {
  upstream backend { server backend:4000; }
  upstream frontend { server frontend:80; }

  # Redirect all HTTP traffic to HTTPS
  server {
    listen 80;
    server_name amrut-tasks.duckdns.org;
    return 301 https://$host$request_uri;
  }

  # Serve HTTPS
  server {
    listen 443 ssl;
    server_name amrut-tasks.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/amrut-tasks.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/amrut-tasks.duckdns.org/privkey.pem;

    location /api/ {
      proxy_pass         http://backend;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    location / {
      proxy_pass         http://frontend;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
  }
}